/* 자동 생성: portal_export.py — 직접 편집하지 마세요. 출처: briefing_latest.json + catalog.json */
window.PORTAL_DATA = {
  "generatedAt": "2026-06-10",
  "source": "나라장터(조달청) 입찰공고정보서비스",
  "analyzedBy": "Claude Code (무료 경로)",
  "total": 48,
  "refDate": "2026-06-15",
  "sourceFile": "briefing_latest.json",
  "bids": [
    {
      "id": "R26BK01551871",
      "name": "2026 한양대에리카 데이터보안활용사업단 온라인 공개강좌(K-MOOC) 교과목 콘텐츠 개발 용역(AI활용클라우드입문)",
      "org": "한양대학교 에리카산학협력단",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01551871&bidPbancOrd=001",
      "deadline": "2026-06-08 17:00:00",
      "security": false,
      "grade": "제외",
      "category": "교육콘텐츠",
      "reason": "온라인 강좌 콘텐츠 개발 — 보안 솔루션 무관.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562406",
      "name": "K-RMF 보안통제항목 표준화 연구",
      "org": "국방기술품질원",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562406&bidPbancOrd=000",
      "deadline": "2026-06-16 10:00:00",
      "security": true,
      "grade": "보안주제/매칭약함",
      "category": "보안 거버넌스",
      "reason": "보안통제 표준화 '연구' — 솔루션 도입 아님.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562656",
      "name": "[재공고]가천대학교 글로벌캠퍼스 후문 도로 통제 보안 및 토지관리 용역",
      "org": "가천대학교",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562656&bidPbancOrd=000",
      "deadline": "",
      "security": false,
      "grade": "제외",
      "category": "물리보안",
      "reason": "도로 통제·경비 — 물리보안(정보보안 아님).",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562848",
      "name": "2026년 보안관제 위탁운영",
      "org": "한국장학재단",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562848&bidPbancOrd=000",
      "deadline": "2026-07-16 11:00:00",
      "security": true,
      "grade": "영업대상",
      "category": "보안관제(SOC)",
      "reason": "보안관제 위탁운영 = SOC 서비스 직접.",
      "products": [
        "(예시) 보안관제 서비스 SOC-Guard"
      ],
      "match": [
        "24x7 관제·SIEM·침해대응(IR)과 직접 부합"
      ],
      "crosssell": "",
      "need": "24시간 위협 모니터링·침해대응 위탁",
      "strength": "24x7 관제 + SIEM 탐지 + 전담 IR팀 일원화",
      "diff": "국가 사이버안전 매뉴얼 기반 대응, 공공 전담팀",
      "talk": "장학재단은 대규모 개인정보를 다뤄 관제 품질이 핵심입니다. SOC-Guard는 공공 전담팀과 표준 프로세스로 탐지·대응 공백을 없앱니다."
    },
    {
      "id": "R26BK01563108",
      "name": "커넥티비티 단말기 연동 보안 시험환경 구축 및 분석 용역",
      "org": "한국교통안전공단 자동차안전연구원",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01563108&bidPbancOrd=000",
      "deadline": "2026-06-16 10:00:00",
      "security": true,
      "grade": "보안주제/매칭약함",
      "category": "OT 보안",
      "reason": "차량 단말 보안 시험환경 — 제품군 밖 연구.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01563476",
      "name": "2026년 노후 보안장비 교체 및 사이버보안체계 강화사업",
      "org": "조달청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01563476&bidPbancOrd=000",
      "deadline": "2026-06-08 14:00:00",
      "security": true,
      "grade": "영업대상",
      "category": "방화벽",
      "reason": "노후 보안장비 교체 + 체계 강화 = 경계보안 교체.",
      "products": [
        "(예시) 차세대 방화벽 NGFW-X"
      ],
      "match": [
        "노후 방화벽 교체 + IPS·앱제어·VPN 통합"
      ],
      "crosssell": "",
      "need": "노후 경계보안 장비 교체·체계 강화",
      "strength": "CC인증 보유, 교체 사업 레퍼런스 다수",
      "diff": "공공 보안적합성 검증(CC인증)·국정원 검증필 암호모듈",
      "talk": "장비 교체는 적합성 인증과 무중단 전환이 핵심입니다. NGFW-X는 CC인증으로 교체 리스크를 줄입니다."
    },
    {
      "id": "R26BK01552791",
      "name": "‘26년 주요정보통신기반시설 취약점 분석 및 정보보안 컨설팅 사업",
      "org": "조달청 충북지방조달청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01552791&bidPbancOrd=000",
      "deadline": "2026-06-16 10:00:00",
      "security": true,
      "grade": "영업대상",
      "category": "정보보호 컨설팅",
      "reason": "기반시설 취약점 분석 + 정보보안 컨설팅 = 보안 진단 핵심.",
      "products": [
        "(예시) 정보보호 컨설팅 ISMS-Care"
      ],
      "match": [
        "기반시설 취약점 진단·모의해킹·정책수립 부합"
      ],
      "crosssell": "",
      "need": "기반시설 취약점을 법적 기준으로 진단·컨설팅",
      "strength": "공공 기반시설 진단 경험과 진단원 다수 보유",
      "diff": "진단→개선과제→이행점검 연결",
      "talk": "기반시설 취약점 분석은 진단 품질과 공공 레퍼런스가 핵심입니다. ISMS-Care는 진단을 넘어 개선·이행점검까지 연결합니다."
    },
    {
      "id": "R26BK01562528",
      "name": "세종 정보보호 인재양성 종합 교육 운영 용역",
      "org": "재단법인 세종테크노파크",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562528&bidPbancOrd=000",
      "deadline": "2026-06-16 14:00:00",
      "security": true,
      "grade": "보안주제/매칭약함",
      "category": "보안 교육",
      "reason": "정보보호 교육 운영 — 솔루션 도입 아님.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01561722",
      "name": "2026년 정보보호시스템 통합 유지관리 용역",
      "org": "조달청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01561722&bidPbancOrd=000",
      "deadline": "2026-07-01 10:00:00",
      "security": true,
      "grade": "영업대상",
      "category": "보안 유지관리",
      "reason": "정보보호시스템 통합 유지관리 = 보안장비·운영 유지.",
      "products": [
        "(예시) 보안관제 서비스 SOC-Guard",
        "(예시) 차세대 방화벽 NGFW-X"
      ],
      "match": [
        "운영·모니터링 포함 통합 유지관리",
        "경계보안 장비 유지·업데이트"
      ],
      "crosssell": "",
      "need": "다수 정보보호시스템의 안정적 통합 유지관리",
      "strength": "관제+장비 운영을 단일 SLA로 묶음",
      "diff": "장애 대응 표준 프로세스 + 폐쇄망 업데이트",
      "talk": "여러 보안시스템을 따로 관리하면 사각지대가 생깁니다. 관제와 장비 운영을 단일 SLA로 묶어 공백을 없앱니다."
    },
    {
      "id": "R26BK01563574",
      "name": "2026년 소방청 개인정보보호 컨설팅",
      "org": "소방청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01563574&bidPbancOrd=000",
      "deadline": "2026-07-16 10:00:00",
      "security": true,
      "grade": "영업대상",
      "category": "정보보호 컨설팅",
      "reason": "개인정보보호 컨설팅 = 정보보호 컨설팅 직접.",
      "products": [
        "(예시) 정보보호 컨설팅 ISMS-Care"
      ],
      "match": [
        "개인정보 관리체계 진단·개선 컨설팅"
      ],
      "crosssell": "",
      "need": "개인정보 처리 점검·개선으로 규제 대응",
      "strength": "ISMS-P 인증 컨설팅 표준 방법론",
      "diff": "심사 지적 패턴 기반 실효 개선",
      "talk": "소방청은 민원·현장 개인정보가 많습니다. 형식 점검이 아니라 실제로 통과·개선되는 체계를 만듭니다."
    },
    {
      "id": "R26BK01562185",
      "name": "나라사랑카드시스템 간편인증 서비스 사업자 선정사업",
      "org": "군인공제회C_C",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562185&bidPbancOrd=000",
      "deadline": "2026-07-16 10:00:00",
      "security": true,
      "grade": "영업대상",
      "category": "접근통제(IAM)",
      "reason": "간편인증 = 인증·접근통제 영역.",
      "products": [
        "(예시) 통합 접근통제 IAM-Pro"
      ],
      "match": [
        "MFA·SSO·계정관리로 간편인증 충족"
      ],
      "crosssell": "",
      "need": "안전하고 편리한 사용자 간편인증",
      "strength": "MFA·SSO·계정관리 통합, 공공 표준 연계",
      "diff": "GPKI 연계 및 감사로그 자동화",
      "talk": "간편인증은 편의성과 보안의 균형이 관건입니다. IAM-Pro는 MFA·SSO에 감사 추적까지 자동화합니다."
    },
    {
      "id": "R26BK01561970",
      "name": "[한국소방시설협회] 정보시스템 기능 고도화 사업",
      "org": "조달청 대전지방조달청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01561970&bidPbancOrd=000",
      "deadline": "2026-06-26 10:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "정보시스템 구축",
      "reason": "정보시스템 고도화 — 직접 보안은 아니나 보안 점검 동반 가능.",
      "products": [],
      "match": [],
      "crosssell": "고도화 범위에 보안 취약점 점검·시큐어코딩·접근통제 보강을 끼워 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01561756",
      "name": "방사능영향평가 정보시스템 운영 및 유지보수",
      "org": "조달청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01561756&bidPbancOrd=000",
      "deadline": "2026-06-08 15:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "정보시스템 구축",
      "reason": "정보시스템 운영·유지보수 — 보안 유지관리 크로스셀.",
      "products": [],
      "match": [],
      "crosssell": "운영 유지보수에 보안패치·로그모니터링을 묶어 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01561435",
      "name": "웹기반 정보시스템 접근성 개선",
      "org": "한국보건의료인국가시험원",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01561435&bidPbancOrd=000",
      "deadline": "2026-06-16 10:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "홈페이지/웹",
      "reason": "웹 정보시스템 개선 — 웹 취약점 점검 크로스셀.",
      "products": [],
      "match": [],
      "crosssell": "접근성 개선과 함께 웹 취약점 진단(모의해킹) 동반 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562718",
      "name": "집단에너지 종합정보시스템 유지관리",
      "org": "한국에너지공단",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562718&bidPbancOrd=000",
      "deadline": "2026-06-16 10:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "정보시스템 구축",
      "reason": "종합정보시스템 유지관리 — 보안 유지 크로스셀.",
      "products": [],
      "match": [],
      "crosssell": "시스템 유지관리에 보안관제·취약점 점검 연계",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562892",
      "name": "통합 행정정보시스템 교체 및 고도화 용역",
      "org": "강원특별자치도",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562892&bidPbancOrd=000",
      "deadline": "2026-06-05 15:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "전자정부",
      "reason": "행정정보시스템 교체·고도화 — 보안적합성·망분리 동반.",
      "products": [],
      "match": [],
      "crosssell": "교체 사업에 보안적합성 검증·망분리 설계 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562725",
      "name": "국립금오공과대학교 통합정보시스템 유지관리 사업",
      "org": "조달청 대구지방조달청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562725&bidPbancOrd=000",
      "deadline": "2026-06-16 10:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "정보시스템 구축",
      "reason": "대학 통합정보시스템 유지관리 — 보안 유지 크로스셀.",
      "products": [],
      "match": [],
      "crosssell": "유지관리에 계정·접근통제(IAM) 점검 연계",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562491",
      "name": "재난희생자 신원확인시스템 구축 사업(SCAS고도화)",
      "org": "조달청 서울지방조달청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562491&bidPbancOrd=000",
      "deadline": "2026-06-18 10:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "정보시스템 구축",
      "reason": "신원확인시스템 — 민감정보 처리로 개인정보 보안 동반.",
      "products": [],
      "match": [],
      "crosssell": "신원·생체정보 처리에 개인정보 암호화·접근통제 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01563111",
      "name": "동산스포츠_ AI 기반 수요 예측을 통한 생산 및 재고 운영 효율화 시스템 구축",
      "org": "(주)한국능률협회컨설팅",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01563111&bidPbancOrd=000",
      "deadline": "2026-06-16 10:00:00",
      "security": false,
      "grade": "제외",
      "category": "무관",
      "reason": "생산·재고 시스템 — 보안 무관.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01563165",
      "name": "2026 경기도 사회적경제조직 실태조사 및 DB관리시스템 구축 용역(재공고)",
      "org": "재단법인경기도사회적경제원",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01563165&bidPbancOrd=000",
      "deadline": "2026-06-16 11:00:00",
      "security": false,
      "grade": "제외",
      "category": "무관",
      "reason": "실태조사 DB관리 — 보안 솔루션 무관.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01552806",
      "name": "AI기반 빅데이터 통계시스템 구축 및 체인포털 서비스 개선사업 감리 용역",
      "org": "조달청 부산지방조달청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01552806&bidPbancOrd=000",
      "deadline": "2026-06-23 10:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "정보시스템 구축",
      "reason": "빅데이터 시스템 구축 감리 — 데이터 보안 크로스셀.",
      "products": [],
      "match": [],
      "crosssell": "구축 감리 시 데이터 접근통제·개인정보 비식별 점검 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01563570",
      "name": "㈜브레이브컴퍼니빅데이터 통합 BI 시스템 구축",
      "org": "(주)한국능률협회컨설팅",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01563570&bidPbancOrd=000",
      "deadline": "2026-06-16 10:00:00",
      "security": false,
      "grade": "제외",
      "category": "무관",
      "reason": "민간 BI 시스템 — 보안 무관.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01561893",
      "name": "2026년 대구국토 관내 비탈면 모니터링 시스템 구축 용역",
      "org": "국토교통부 부산지방국토관리청 대구국토관리사무소",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01561893&bidPbancOrd=000",
      "deadline": "2026-06-15 15:00:00",
      "security": false,
      "grade": "제외",
      "category": "무관",
      "reason": "비탈면 모니터링 — '시스템' 키워드 오탐.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01563032",
      "name": "국립민속박물관 전산시스템 이전 구축 ISP 수립 사업",
      "org": "조달청 서울지방조달청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01563032&bidPbancOrd=000",
      "deadline": "2026-06-17 10:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "정보시스템 구축",
      "reason": "ISP 수립 — 보안 아키텍처 설계 동반 가능.",
      "products": [],
      "match": [],
      "crosssell": "ISP에 보안 아키텍처·망구성 설계 포함 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01563323",
      "name": "대한장애인체육회 전산실 통합 유지보수 및 관리용역",
      "org": "대한장애인체육회",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01563323&bidPbancOrd=000",
      "deadline": "2026-06-16 14:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "네트워크/인프라",
      "reason": "전산실 인프라 유지보수 — 경계보안·관제 크로스셀.",
      "products": [],
      "match": [],
      "crosssell": "인프라 유지보수에 방화벽 정책·로그관제 연계",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01552804",
      "name": "체인포털 클라우드 기반 이중화 구축 감리용역",
      "org": "조달청 부산지방조달청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01552804&bidPbancOrd=000",
      "deadline": "2026-06-23 10:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "클라우드 전환",
      "reason": "클라우드 이중화 구축 — 클라우드 보안 크로스셀.",
      "products": [],
      "match": [],
      "crosssell": "이중화 설계에 클라우드 보안형상·접근통제 동반 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01559196",
      "name": "AI 레드팀 테스트베드 환경 조성을 위한 클라우드 서비스 구매",
      "org": "조달청 광주지방조달청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01559196&bidPbancOrd=000",
      "deadline": "2026-06-26 10:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "클라우드 전환",
      "reason": "AI 레드팀 환경 — 보안 시험과 직접 인접.",
      "products": [],
      "match": [],
      "crosssell": "레드팀 환경에 모의해킹·취약점 진단 역량 연계",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562685",
      "name": "(긴급)아산시 강소형 스마트시티 조성사업 [메타버스 플랫폼 구축 용역]",
      "org": "(주)제일엔지니어링종합건축사사무소",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562685&bidPbancOrd=000",
      "deadline": "2026-06-15 16:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "스마트시티",
      "reason": "스마트시티 플랫폼 — IoT·영상 보안 동반.",
      "products": [],
      "match": [],
      "crosssell": "스마트시티 플랫폼에 IoT·영상정보 보안, 통합관제 보안 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562470",
      "name": "2026 월드 스마트시티 엑스포 홍보관 구축·운영 용역",
      "org": "조달청 대구지방조달청",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562470&bidPbancOrd=000",
      "deadline": "2026-06-17 10:00:00",
      "security": false,
      "grade": "제외",
      "category": "무관",
      "reason": "엑스포 홍보관 운영 — 보안 무관.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01543978",
      "name": "아산시 강소형 스마트시티 조성사업 [시설물 위치기반 표준 서비스 플랫폼 구축 및 서비스 확산 용역]",
      "org": "(주)제일엔지니어링종합건축사사무소",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01543978&bidPbancOrd=001",
      "deadline": "2026-06-05 16:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "스마트시티",
      "reason": "스마트시티 플랫폼 — IoT·영상 보안 동반.",
      "products": [],
      "match": [],
      "crosssell": "스마트시티 플랫폼에 IoT·영상정보 보안, 통합관제 보안 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01563692",
      "name": "재공고 아산시 강소형 스마트시티 조성사업 [시설물 위치기반 표준 서비스 플랫폼 구축 및 서비스 확산 용역]",
      "org": "(주)제일엔지니어링종합건축사사무소",
      "type": "용역",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01563692&bidPbancOrd=000",
      "deadline": "2026-06-09 17:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "스마트시티",
      "reason": "스마트시티 플랫폼 — IoT·영상 보안 동반.",
      "products": [],
      "match": [],
      "crosssell": "스마트시티 플랫폼에 IoT·영상정보 보안, 통합관제 보안 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562603",
      "name": "AWS 보안관제시스템 소프트웨어 도입",
      "org": "사단법인 금융보안원",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562603&bidPbancOrd=000",
      "deadline": "",
      "security": true,
      "grade": "영업대상",
      "category": "보안관제(SOC)",
      "reason": "클라우드(AWS) 보안관제 SW = SOC 솔루션.",
      "products": [
        "(예시) 보안관제 서비스 SOC-Guard"
      ],
      "match": [
        "클라우드 SIEM 기반 위협탐지·관제"
      ],
      "crosssell": "",
      "need": "AWS 환경 보안 위협 통합 관제",
      "strength": "클라우드 로그 수집·SIEM 탐지·대응 통합",
      "diff": "금융권 컴플라이언스 대응 경험",
      "talk": "클라우드는 위협 양상이 다릅니다. SOC-Guard는 AWS 로그 기반 탐지에 금융권 컴플라이언스 경험을 더합니다."
    },
    {
      "id": "R26BK01547090",
      "name": "보안 소프트웨어 구입",
      "org": "중부기술교육원",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01547090&bidPbancOrd=000",
      "deadline": "2026-06-16 10:00:00",
      "security": true,
      "grade": "영업대상",
      "category": "백신/EDR",
      "reason": "보안 소프트웨어 구입 = 엔드포인트/보안 SW.",
      "products": [
        "(예시) 엔드포인트 보안 EDR-Shield"
      ],
      "match": [
        "단말 보안 SW 도입 요구 충족"
      ],
      "crosssell": "",
      "need": "단말 보안 소프트웨어 도입",
      "strength": "경량 에이전트·랜섬웨어 차단·중앙관리",
      "diff": "폐쇄망 업데이트 지원",
      "talk": "보안 SW는 운영 부담이 관건입니다. EDR-Shield는 경량 에이전트와 폐쇄망 업데이트로 운영을 단순화합니다."
    },
    {
      "id": "R26BK01562564",
      "name": "노후 정보보호시스템 교체 구축",
      "org": "사단법인 금융보안원",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562564&bidPbancOrd=000",
      "deadline": "",
      "security": true,
      "grade": "영업대상",
      "category": "방화벽",
      "reason": "노후 정보보호시스템 교체 구축 = 보안장비 교체.",
      "products": [
        "(예시) 차세대 방화벽 NGFW-X"
      ],
      "match": [
        "노후 보안시스템 교체·통합"
      ],
      "crosssell": "",
      "need": "노후 정보보호시스템 교체·현행화",
      "strength": "CC인증 장비, 교체 전환 무중단 설계",
      "diff": "공공 보안적합성 검증 보유",
      "talk": "노후 보안시스템은 그 자체가 취약점입니다. CC인증 NGFW-X로 안전하게 교체합니다."
    },
    {
      "id": "R26BK01562930",
      "name": "2026년 유료 대상포진 예방접종 백신 구입-224",
      "org": "전라남도 해남군",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562930&bidPbancOrd=000",
      "deadline": "2026-06-15 10:00:00",
      "security": false,
      "grade": "제외",
      "category": "의료백신",
      "reason": "예방접종 백신 — 의료(antivirus 아님).",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01563066",
      "name": "금융결제원 오픈소스 SW 취약점 대응체계 구축 관련 IT자원 도입",
      "org": "금융결제원",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01563066&bidPbancOrd=000",
      "deadline": "",
      "security": true,
      "grade": "영업대상",
      "category": "정보보호 컨설팅",
      "reason": "오픈소스 SW 취약점 대응체계 = 보안 진단·컨설팅.",
      "products": [
        "(예시) 정보보호 컨설팅 ISMS-Care"
      ],
      "match": [
        "SW 취약점 진단·대응 프로세스 수립"
      ],
      "crosssell": "",
      "need": "오픈소스 SW 취약점 식별·대응 체계 구축",
      "strength": "취약점 진단·SBOM·대응 프로세스 경험",
      "diff": "금융권 컴플라이언스 연계",
      "talk": "오픈소스 취약점은 상시 관리가 핵심입니다. 진단에 그치지 않고 지속 대응 체계를 함께 설계합니다."
    },
    {
      "id": "R26BK01562458",
      "name": "2026년도 지진화산정보시스템 노후 인프라 교체",
      "org": "조달청",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562458&bidPbancOrd=000",
      "deadline": "2026-06-17 10:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "네트워크/인프라",
      "reason": "노후 인프라 교체 — 보안장비 동반 교체 가능.",
      "products": [],
      "match": [],
      "crosssell": "인프라 교체에 차세대 방화벽·접근통제 동반",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01563864",
      "name": "스마트도시통합센터 정보시스템 테이프 백업장비 구축",
      "org": "경기도 안양시",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01563864&bidPbancOrd=000",
      "deadline": "2026-06-15 10:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "데이터센터",
      "reason": "백업장비 구축 — 랜섬웨어 대비 백업·DR 보안 크로스셀.",
      "products": [],
      "match": [],
      "crosssell": "백업 구성에 랜섬웨어 대비 불변백업·접근통제 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562059",
      "name": "빛마루도서관 정보화 시스템 구축",
      "org": "경기도 광명시",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562059&bidPbancOrd=000",
      "deadline": "",
      "security": false,
      "grade": "연관기회",
      "category": "정보시스템 구축",
      "reason": "도서관 정보화 시스템 구축 — 보안 설계 동반.",
      "products": [],
      "match": [],
      "crosssell": "정보화 구축에 경계보안·계정관리 기본 설계 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562847",
      "name": "이동식 토양현장진단 시스템 구축사업 장비 구입",
      "org": "충청남도 공주시 농업기술센터",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562847&bidPbancOrd=000",
      "deadline": "2026-06-08 16:00:00",
      "security": false,
      "grade": "제외",
      "category": "무관",
      "reason": "토양 진단 장비 — '시스템' 키워드 오탐.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01564278",
      "name": "3MN 고정밀 커스텀 하중 센서 제작 및 TDAS G5 연결 시스템 구축",
      "org": "한국철도기술연구원",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01564278&bidPbancOrd=000",
      "deadline": "2026-06-11 11:00:00",
      "security": false,
      "grade": "제외",
      "category": "무관",
      "reason": "하중 센서 시스템 — '시스템' 키워드 오탐.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01539898",
      "name": "2026년도 서산성봉학교 통학차량 구조변경(휠체어리프트 설치 및 어린이보호시스템 구축) 소액수의 견적 제출 공고",
      "org": "충청남도교육청 서산성봉학교",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01539898&bidPbancOrd=000",
      "deadline": "2026-06-12 10:00:00",
      "security": false,
      "grade": "제외",
      "category": "무관",
      "reason": "통학차량 구조변경 — '시스템' 키워드 오탐.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562538",
      "name": "병렬 전산해석 및 격자생성을 위한 CFD 프로그램 병렬 라이선스 구매",
      "org": "한국항공우주연구원",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562538&bidPbancOrd=000",
      "deadline": "2026-06-16 10:00:00",
      "security": false,
      "grade": "제외",
      "category": "무관",
      "reason": "CFD 라이선스 — '전산' 키워드 오탐.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562750",
      "name": "국립목포해양대학교 전산유체역학(CFD) 해석 소프트웨어 구매",
      "org": "국립목포해양대학교 산학협력단",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562750&bidPbancOrd=000",
      "deadline": "2026-06-12 14:00:00",
      "security": false,
      "grade": "제외",
      "category": "무관",
      "reason": "CFD 해석 SW — '전산' 키워드 오탐.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01563469",
      "name": "나사렛대학교 네트워크 트래픽 제어시스템 고도화 사업",
      "org": "나사렛대학교",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01563469&bidPbancOrd=000",
      "deadline": "2026-06-17 10:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "네트워크/인프라",
      "reason": "네트워크 트래픽 제어 — 방화벽·IPS와 직접 인접.",
      "products": [],
      "match": [],
      "crosssell": "트래픽 제어에 차세대 방화벽·IPS 통합 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01558507",
      "name": "글로컬대학30 월드클래스 도전학과 관련 실험실습기자재 구매(컴퓨터 서버)",
      "org": "충북대학교 의과대학",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01558507&bidPbancOrd=000",
      "deadline": "2026-06-09 11:00:00",
      "security": false,
      "grade": "제외",
      "category": "무관",
      "reason": "컴퓨터 서버 실습장비 — '서버' 키워드 오탐.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01564083",
      "name": "조립PC(연구용 GPU서버)",
      "org": "광운대학교 산학협력단",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01564083&bidPbancOrd=000",
      "deadline": "",
      "security": false,
      "grade": "제외",
      "category": "무관",
      "reason": "연구용 GPU 서버 — '서버' 키워드 오탐.",
      "products": [],
      "match": [],
      "crosssell": "",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    },
    {
      "id": "R26BK01562403",
      "name": "제주공항 항행안전시설 CCTV 교체",
      "org": "한국공항공사 제주공항",
      "type": "물품",
      "url": "https://www.g2b.go.kr/link/PNPE027_01/single/?bidPbancNo=R26BK01562403&bidPbancOrd=000",
      "deadline": "2026-06-05 15:00:00",
      "security": false,
      "grade": "연관기회",
      "category": "통합관제/영상",
      "reason": "CCTV 교체 — 영상정보 보안·관제 크로스셀.",
      "products": [],
      "match": [],
      "crosssell": "CCTV 교체에 영상 접근통제·영상보안 솔루션 제안",
      "need": "",
      "strength": "",
      "diff": "",
      "talk": ""
    }
  ],
  "products": [
    {
      "name": "(예시) 차세대 방화벽 NGFW-X",
      "category": "네트워크 보안",
      "features": [
        "침입탐지/차단(IPS)",
        "애플리케이션 제어",
        "VPN",
        "위협 인텔리전스"
      ],
      "fits": [
        "방화벽 교체",
        "경계 보안 강화",
        "망분리 구간 보호"
      ],
      "diff": "공공기관 보안적합성 검증(CC인증) 보유, 국정원 검증필 암호모듈 탑재"
    },
    {
      "name": "(예시) 망분리 솔루션 NetSep",
      "category": "망분리",
      "features": [
        "물리/논리 망분리",
        "망간자료전송(CDR)",
        "반입출 통제"
      ],
      "fits": [
        "내외부망 분리",
        "망연계",
        "자료 반출입 통제"
      ],
      "diff": "공공 표준 망연계 가이드 준수, 대규모 기관 레퍼런스 다수"
    },
    {
      "name": "(예시) 통합 접근통제 IAM-Pro",
      "category": "접근통제(IAM)",
      "features": [
        "계정/권한관리(IGA)",
        "다중인증(MFA)",
        "특권계정관리(PAM)",
        "SSO"
      ],
      "fits": [
        "계정관리 체계화",
        "권한 최소화",
        "관리자 접근통제"
      ],
      "diff": "행정전자서명(GPKI) 연계, 감사로그 자동화"
    },
    {
      "name": "(예시) 보안관제 서비스 SOC-Guard",
      "category": "보안관제(SOC)",
      "features": [
        "24x7 관제",
        "SIEM 기반 위협탐지",
        "침해사고 대응(IR)",
        "위협 헌팅"
      ],
      "fits": [
        "보안관제 위탁",
        "침해대응 체계 구축",
        "관제 인력 부족"
      ],
      "diff": "국가 사이버안전 매뉴얼 기반 대응 프로세스, 공공 전담 관제팀"
    },
    {
      "name": "(예시) 엔드포인트 보안 EDR-Shield",
      "category": "백신/EDR",
      "features": [
        "행위기반 위협탐지",
        "랜섬웨어 차단",
        "EDR 가시성",
        "중앙관리"
      ],
      "fits": [
        "백신 교체",
        "단말 보안 강화",
        "랜섬웨어 대응"
      ],
      "diff": "경량 에이전트, 폐쇄망 업데이트 지원"
    },
    {
      "name": "(예시) 정보보호 컨설팅 ISMS-Care",
      "category": "정보보호 컨설팅",
      "features": [
        "ISMS-P 인증 컨설팅",
        "취약점 진단",
        "모의해킹",
        "보안정책 수립"
      ],
      "fits": [
        "정보보호 컨설팅",
        "취약점 점검",
        "인증 대응",
        "보안 진단"
      ],
      "diff": "공공기관 인증 심사 경험 보유, 진단원 다수 보유"
    }
  ]
};
